### PR TITLE
readded badges

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by fgimenez** [comment]
eee

**Comment by yenquins** [comment]
hey!

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Comment by fgimenez** [comment]
test this please

**Pull request closed without merging**
